namespace UaiGranja.Avicultura.Domain.Enums
{
    public enum RacaEnum
    {     
        Mestico = 0,
        CaipiraComum = 1,
        CaipiraPescocoPelado = 2,
        PlymouthRockBarrada = 3,
        RhodeIslandRed = 4,
        NewHampshire = 5,
        Shamo = 6,
        Asil = 7,
        Leghorne = 8,
        Australorp = 9,
        Minorca = 10,
        Sussex = 11,
        Orpington = 12,
        Brahma = 13,
        Cochin = 14,
        GiganteJersey = 15,
        BantamJaponesa = 16,
        TurkenTransilvania = 17,
        Cornish = 18,
        Sumatra = 19,
        AgRoss = 20,
        CobbVantress = 21,
        Hybro = 22,
        IsaVedette = 23,
        MPK = 24,
        Hubbard = 25,
        Arbor = 26,
        Acres = 27,
        AvianShaver = 28,
        Hisex = 29,
        Lohmann = 30,
        Isa = 31,
        HyLine = 32,
        Shaver = 33,
        HNNickChick = 34,
        TetraHarco = 35,
        Embrapa021 = 36,
        S54 = 37,
        Chester = 38,
        Embrapa011 = 39,
        Embrapa031 = 40,
        ParaisoPedrez = 41,
        Embrapa041 = 42,
        FrangoGaucho = 43,
        Acoblack = 44,
        GiganteNegro = 45,
        PesadoVermelho = 46,
        CarijoPesado = 47,
        CarijoPescocoPelado = 48,
        MasterGriss = 49,
        PesadaoVermelho = 50
    }
}
